data_root: /home/pdavies/Documents/era5_daily_files
region: ghana
max_lead_days: 1.0
start_date: '2025-01-01'
end_date: '2025-12-31'
inputs:
- name: cape
  path: era5_cape
  normalisation:
    type: zscore
    stats:
      mean: 680.211181640625
      std: 664.0623168945312
- name: tp
  path: era5_tp
  scale: 1000
  normalisation:
    type: log1p
    stats:
      log1p_mean: 3.052427291870117
      log1p_std: 7.152277946472168
- name: d2m
  path: era5_d2m
  normalisation:
    type: zscore
    stats:
      mean: 294.8641052246094
      std: 5.341831207275391
- name: tcw
  path: era5_tcw
  normalisation:
    type: zscore
    stats:
      mean: 1098.9129638671875
      std: 291.0619812011719
- name: u10
  path: era5_u10
  normalisation:
    type: zscore
    stats:
      mean: 0.9532492756843567
      std: 1.4311678409576416
- name: v10
  path: era5_v10
  normalisation:
    type: zscore
    stats:
      mean: 1.534293532371521
      std: 1.391543984413147
target:
  name: precipitation
  path: imerg
  normalisation:
    type: log1p
    stats:
      log1p_mean: 0.7147529721260071
      log1p_std: 1.0967700481414795
additional_data:
- latlon
- day_of_year
